version: "3.7"

services:
  postgres:
    image: postgres:9.6
    container_name: api_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes: 
  postgres-data: