version: "3.7"

services:
  postgres:
    image: postgres:9.6
    container_name: api_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Ab12345@
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes: 
  postgres-data: